// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// ListHasMovie represents a row from public.list_has_movie.
type ListHasMovie struct {
	IDList   string // id_list
	Username string // username
	ImdbID   string // imdb_id
	Title    string // title
	Erased   uint8  // erased

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the ListHasMovie exists in the database.
func (lhm *ListHasMovie) Exists() bool {
	return lhm._exists
}

// Deleted provides information if the ListHasMovie has been deleted from the database.
func (lhm *ListHasMovie) Deleted() bool {
	return lhm._deleted
}

// Insert inserts the ListHasMovie to the database.
func (lhm *ListHasMovie) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if lhm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.list_has_movie (` +
		`id_list, username, imdb_id, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING title`

	// run query
	XOLog(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Erased)
	err = db.QueryRow(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Erased).Scan(&lhm.Title)
	if err != nil {
		return err
	}

	// set existence
	lhm._exists = true

	return nil
}

// Update updates the ListHasMovie in the database.
func (lhm *ListHasMovie) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !lhm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if lhm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.list_has_movie SET (` +
		`id_list, username, imdb_id, erased` +
		`) = ( ` +
		`$1, $2, $3, $4` +
		`) WHERE title = $5`

	// run query
	XOLog(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Erased, lhm.Title)
	_, err = db.Exec(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Erased, lhm.Title)
	return err
}

// Save saves the ListHasMovie to the database.
func (lhm *ListHasMovie) Save(db XODB) error {
	if lhm.Exists() {
		return lhm.Update(db)
	}

	return lhm.Insert(db)
}

// Upsert performs an upsert for ListHasMovie.
//
// NOTE: PostgreSQL 9.5+ only
func (lhm *ListHasMovie) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if lhm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.list_has_movie (` +
		`id_list, username, imdb_id, title, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) ON CONFLICT (title) DO UPDATE SET (` +
		`id_list, username, imdb_id, title, erased` +
		`) = (` +
		`EXCLUDED.id_list, EXCLUDED.username, EXCLUDED.imdb_id, EXCLUDED.title, EXCLUDED.erased` +
		`)`

	// run query
	XOLog(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Title, lhm.Erased)
	_, err = db.Exec(sqlstr, lhm.IDList, lhm.Username, lhm.ImdbID, lhm.Title, lhm.Erased)
	if err != nil {
		return err
	}

	// set existence
	lhm._exists = true

	return nil
}

// Delete deletes the ListHasMovie from the database.
func (lhm *ListHasMovie) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !lhm._exists {
		return nil
	}

	// if deleted, bail
	if lhm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.list_has_movie WHERE title = $1`

	// run query
	XOLog(sqlstr, lhm.Title)
	_, err = db.Exec(sqlstr, lhm.Title)
	if err != nil {
		return err
	}

	// set deleted
	lhm._deleted = true

	return nil
}

// List returns the List associated with the ListHasMovie's Username (username).
//
// Generated from foreign key 'fk_list_has_movie_list1'.
func (lhm *ListHasMovie) List(db XODB) (*List, error) {
	return ListByUsername(db, lhm.Username)
}

// Movie returns the Movie associated with the ListHasMovie's Title (title).
//
// Generated from foreign key 'fk_list_has_movie_movie1'.
func (lhm *ListHasMovie) Movie(db XODB) (*Movie, error) {
	return MovieByTitle(db, lhm.Title)
}

// ListHasMovieByIDListImdbIDTitle retrieves a row from 'public.list_has_movie' as a ListHasMovie.
//
// Generated from index 'list_has_movie_pkey'.
func ListHasMovieByIDListImdbIDTitle(db XODB, idList string, imdbID string, title string) (*ListHasMovie, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id_list, username, imdb_id, title, erased ` +
		`FROM public.list_has_movie ` +
		`WHERE id_list = $1 AND imdb_id = $2 AND title = $3`

	// run query
	XOLog(sqlstr, idList, imdbID, title)
	lhm := ListHasMovie{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, idList, imdbID, title).Scan(&lhm.IDList, &lhm.Username, &lhm.ImdbID, &lhm.Title, &lhm.Erased)
	if err != nil {
		return nil, err
	}

	return &lhm, nil
}
