// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// List represents a row from public.list.
type List struct {
	IDList      string // id_list
	Name        string // name
	Description string // description
	Username    string // username

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the List exists in the database.
func (l *List) Exists() bool {
	return l._exists
}

// Deleted provides information if the List has been deleted from the database.
func (l *List) Deleted() bool {
	return l._deleted
}

// Insert inserts the List to the database.
func (l *List) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if l._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.list (` +
		`id_list, name, description` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) RETURNING username`

	// run query
	XOLog(sqlstr, l.IDList, l.Name, l.Description)
	err = db.QueryRow(sqlstr, l.IDList, l.Name, l.Description).Scan(&l.Username)
	if err != nil {
		return err
	}

	// set existence
	l._exists = true

	return nil
}

// Update updates the List in the database.
func (l *List) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !l._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if l._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.list SET (` +
		`id_list, name, description` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE username = $4`

	// run query
	XOLog(sqlstr, l.IDList, l.Name, l.Description, l.Username)
	_, err = db.Exec(sqlstr, l.IDList, l.Name, l.Description, l.Username)
	return err
}

// Save saves the List to the database.
func (l *List) Save(db XODB) error {
	if l.Exists() {
		return l.Update(db)
	}

	return l.Insert(db)
}

// Upsert performs an upsert for List.
//
// NOTE: PostgreSQL 9.5+ only
func (l *List) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if l._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.list (` +
		`id_list, name, description, username` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (username) DO UPDATE SET (` +
		`id_list, name, description, username` +
		`) = (` +
		`EXCLUDED.id_list, EXCLUDED.name, EXCLUDED.description, EXCLUDED.username` +
		`)`

	// run query
	XOLog(sqlstr, l.IDList, l.Name, l.Description, l.Username)
	_, err = db.Exec(sqlstr, l.IDList, l.Name, l.Description, l.Username)
	if err != nil {
		return err
	}

	// set existence
	l._exists = true

	return nil
}

// Delete deletes the List from the database.
func (l *List) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !l._exists {
		return nil
	}

	// if deleted, bail
	if l._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.list WHERE username = $1`

	// run query
	XOLog(sqlstr, l.Username)
	_, err = db.Exec(sqlstr, l.Username)
	if err != nil {
		return err
	}

	// set deleted
	l._deleted = true

	return nil
}

// UserAccount returns the UserAccount associated with the List's Username (username).
//
// Generated from foreign key 'fk_list_user_account1'.
func (l *List) UserAccount(db XODB) (*UserAccount, error) {
	return UserAccountByUsername(db, l.Username)
}

// ListByIDListUsername retrieves a row from 'public.list' as a List.
//
// Generated from index 'list_pkey'.
func ListByIDListUsername(db XODB, idList string, username string) (*List, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id_list, name, description, username ` +
		`FROM public.list ` +
		`WHERE id_list = $1 AND username = $2`

	// run query
	XOLog(sqlstr, idList, username)
	l := List{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, idList, username).Scan(&l.IDList, &l.Name, &l.Description, &l.Username)
	if err != nil {
		return nil, err
	}

	return &l, nil
}
