// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// UserNextviewsMovie represents a row from public.user_nextviews_movie.
type UserNextviewsMovie struct {
	Username string // username
	ImdbID   string // imdb_id
	Title    string // title
	Ereased  uint8  // ereased

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UserNextviewsMovie exists in the database.
func (unm *UserNextviewsMovie) Exists() bool {
	return unm._exists
}

// Deleted provides information if the UserNextviewsMovie has been deleted from the database.
func (unm *UserNextviewsMovie) Deleted() bool {
	return unm._deleted
}

// Insert inserts the UserNextviewsMovie to the database.
func (unm *UserNextviewsMovie) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if unm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_nextviews_movie (` +
		`username, imdb_id, ereased` +
		`) VALUES (` +
		`$1, $2, $3` +
		`) RETURNING title`

	// run query
	XOLog(sqlstr, unm.Username, unm.ImdbID, unm.Ereased)
	err = db.QueryRow(sqlstr, unm.Username, unm.ImdbID, unm.Ereased).Scan(&unm.Title)
	if err != nil {
		return err
	}

	// set existence
	unm._exists = true

	return nil
}

// Update updates the UserNextviewsMovie in the database.
func (unm *UserNextviewsMovie) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !unm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if unm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.user_nextviews_movie SET (` +
		`username, imdb_id, ereased` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE title = $4`

	// run query
	XOLog(sqlstr, unm.Username, unm.ImdbID, unm.Ereased, unm.Title)
	_, err = db.Exec(sqlstr, unm.Username, unm.ImdbID, unm.Ereased, unm.Title)
	return err
}

// Save saves the UserNextviewsMovie to the database.
func (unm *UserNextviewsMovie) Save(db XODB) error {
	if unm.Exists() {
		return unm.Update(db)
	}

	return unm.Insert(db)
}

// Upsert performs an upsert for UserNextviewsMovie.
//
// NOTE: PostgreSQL 9.5+ only
func (unm *UserNextviewsMovie) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if unm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_nextviews_movie (` +
		`username, imdb_id, title, ereased` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (title) DO UPDATE SET (` +
		`username, imdb_id, title, ereased` +
		`) = (` +
		`EXCLUDED.username, EXCLUDED.imdb_id, EXCLUDED.title, EXCLUDED.ereased` +
		`)`

	// run query
	XOLog(sqlstr, unm.Username, unm.ImdbID, unm.Title, unm.Ereased)
	_, err = db.Exec(sqlstr, unm.Username, unm.ImdbID, unm.Title, unm.Ereased)
	if err != nil {
		return err
	}

	// set existence
	unm._exists = true

	return nil
}

// Delete deletes the UserNextviewsMovie from the database.
func (unm *UserNextviewsMovie) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !unm._exists {
		return nil
	}

	// if deleted, bail
	if unm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.user_nextviews_movie WHERE title = $1`

	// run query
	XOLog(sqlstr, unm.Title)
	_, err = db.Exec(sqlstr, unm.Title)
	if err != nil {
		return err
	}

	// set deleted
	unm._deleted = true

	return nil
}

// Movie returns the Movie associated with the UserNextviewsMovie's Title (title).
//
// Generated from foreign key 'fk_user_account_has_movie_movie2'.
func (unm *UserNextviewsMovie) Movie(db XODB) (*Movie, error) {
	return MovieByTitle(db, unm.Title)
}

// UserAccount returns the UserAccount associated with the UserNextviewsMovie's Username (username).
//
// Generated from foreign key 'fk_user_account_has_movie_user_account2'.
func (unm *UserNextviewsMovie) UserAccount(db XODB) (*UserAccount, error) {
	return UserAccountByUsername(db, unm.Username)
}

// UserNextviewsMovieByUsernameImdbIDTitle retrieves a row from 'public.user_nextviews_movie' as a UserNextviewsMovie.
//
// Generated from index 'user_nextviews_movie_pkey'.
func UserNextviewsMovieByUsernameImdbIDTitle(db XODB, username string, imdbID string, title string) (*UserNextviewsMovie, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`username, imdb_id, title, ereased ` +
		`FROM public.user_nextviews_movie ` +
		`WHERE username = $1 AND imdb_id = $2 AND title = $3`

	// run query
	XOLog(sqlstr, username, imdbID, title)
	unm := UserNextviewsMovie{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, username, imdbID, title).Scan(&unm.Username, &unm.ImdbID, &unm.Title, &unm.Ereased)
	if err != nil {
		return nil, err
	}

	return &unm, nil
}
