// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// UserComentMovie represents a row from public.user_coment_movie.
type UserComentMovie struct {
	Username string // username
	ImdbID   string // imdb_id
	Title    string // title
	Coment   string // coment
	Erased   uint8  // erased

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UserComentMovie exists in the database.
func (ucm *UserComentMovie) Exists() bool {
	return ucm._exists
}

// Deleted provides information if the UserComentMovie has been deleted from the database.
func (ucm *UserComentMovie) Deleted() bool {
	return ucm._deleted
}

// Insert inserts the UserComentMovie to the database.
func (ucm *UserComentMovie) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if ucm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_coment_movie (` +
		`username, imdb_id, coment, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING title`

	// run query
	XOLog(sqlstr, ucm.Username, ucm.ImdbID, ucm.Coment, ucm.Erased)
	err = db.QueryRow(sqlstr, ucm.Username, ucm.ImdbID, ucm.Coment, ucm.Erased).Scan(&ucm.Title)
	if err != nil {
		return err
	}

	// set existence
	ucm._exists = true

	return nil
}

// Update updates the UserComentMovie in the database.
func (ucm *UserComentMovie) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ucm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if ucm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.user_coment_movie SET (` +
		`username, imdb_id, coment, erased` +
		`) = ( ` +
		`$1, $2, $3, $4` +
		`) WHERE title = $5`

	// run query
	XOLog(sqlstr, ucm.Username, ucm.ImdbID, ucm.Coment, ucm.Erased, ucm.Title)
	_, err = db.Exec(sqlstr, ucm.Username, ucm.ImdbID, ucm.Coment, ucm.Erased, ucm.Title)
	return err
}

// Save saves the UserComentMovie to the database.
func (ucm *UserComentMovie) Save(db XODB) error {
	if ucm.Exists() {
		return ucm.Update(db)
	}

	return ucm.Insert(db)
}

// Upsert performs an upsert for UserComentMovie.
//
// NOTE: PostgreSQL 9.5+ only
func (ucm *UserComentMovie) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if ucm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_coment_movie (` +
		`username, imdb_id, title, coment, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) ON CONFLICT (title) DO UPDATE SET (` +
		`username, imdb_id, title, coment, erased` +
		`) = (` +
		`EXCLUDED.username, EXCLUDED.imdb_id, EXCLUDED.title, EXCLUDED.coment, EXCLUDED.erased` +
		`)`

	// run query
	XOLog(sqlstr, ucm.Username, ucm.ImdbID, ucm.Title, ucm.Coment, ucm.Erased)
	_, err = db.Exec(sqlstr, ucm.Username, ucm.ImdbID, ucm.Title, ucm.Coment, ucm.Erased)
	if err != nil {
		return err
	}

	// set existence
	ucm._exists = true

	return nil
}

// Delete deletes the UserComentMovie from the database.
func (ucm *UserComentMovie) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ucm._exists {
		return nil
	}

	// if deleted, bail
	if ucm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.user_coment_movie WHERE title = $1`

	// run query
	XOLog(sqlstr, ucm.Title)
	_, err = db.Exec(sqlstr, ucm.Title)
	if err != nil {
		return err
	}

	// set deleted
	ucm._deleted = true

	return nil
}

// Movie returns the Movie associated with the UserComentMovie's Title (title).
//
// Generated from foreign key 'fk_user_account_has_movie1_movie1'.
func (ucm *UserComentMovie) Movie(db XODB) (*Movie, error) {
	return MovieByTitle(db, ucm.Title)
}

// UserAccount returns the UserAccount associated with the UserComentMovie's Username (username).
//
// Generated from foreign key 'fk_user_account_has_movie1_user_account1'.
func (ucm *UserComentMovie) UserAccount(db XODB) (*UserAccount, error) {
	return UserAccountByUsername(db, ucm.Username)
}

// UserComentMovieByUsernameImdbIDTitle retrieves a row from 'public.user_coment_movie' as a UserComentMovie.
//
// Generated from index 'user_coment_movie_pkey'.
func UserComentMovieByUsernameImdbIDTitle(db XODB, username string, imdbID string, title string) (*UserComentMovie, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`username, imdb_id, title, coment, erased ` +
		`FROM public.user_coment_movie ` +
		`WHERE username = $1 AND imdb_id = $2 AND title = $3`

	// run query
	XOLog(sqlstr, username, imdbID, title)
	ucm := UserComentMovie{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, username, imdbID, title).Scan(&ucm.Username, &ucm.ImdbID, &ucm.Title, &ucm.Coment, &ucm.Erased)
	if err != nil {
		return nil, err
	}

	return &ucm, nil
}
