// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// UserScoreMovie represents a row from public.user_score_movie.
type UserScoreMovie struct {
	Username    string  // username
	ID          string  // id
	Score       float64 // score
	Dateandtime int64   // dateandtime
	Erased      bool    // erased

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UserScoreMovie exists in the database.
func (usm *UserScoreMovie) Exists() bool {
	return usm._exists
}

// Deleted provides information if the UserScoreMovie has been deleted from the database.
func (usm *UserScoreMovie) Deleted() bool {
	return usm._deleted
}

// Insert inserts the UserScoreMovie to the database.
func (usm *UserScoreMovie) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if usm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_score_movie (` +
		`username, score, dateandtime, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, usm.Username, usm.Score, usm.Dateandtime, usm.Erased)
	err = db.QueryRow(sqlstr, usm.Username, usm.Score, usm.Dateandtime, usm.Erased).Scan(&usm.ID)
	if err != nil {
		return err
	}

	// set existence
	usm._exists = true

	return nil
}

// Update updates the UserScoreMovie in the database.
func (usm *UserScoreMovie) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !usm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if usm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.user_score_movie SET (` +
		`username, score, dateandtime, erased` +
		`) = ( ` +
		`$1, $2, $3, $4` +
		`) WHERE id = $5`

	// run query
	XOLog(sqlstr, usm.Username, usm.Score, usm.Dateandtime, usm.Erased, usm.ID)
	_, err = db.Exec(sqlstr, usm.Username, usm.Score, usm.Dateandtime, usm.Erased, usm.ID)
	return err
}

// Save saves the UserScoreMovie to the database.
func (usm *UserScoreMovie) Save(db XODB) error {
	if usm.Exists() {
		return usm.Update(db)
	}

	return usm.Insert(db)
}

// Upsert performs an upsert for UserScoreMovie.
//
// NOTE: PostgreSQL 9.5+ only
func (usm *UserScoreMovie) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if usm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_score_movie (` +
		`username, id, score, dateandtime, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`username, id, score, dateandtime, erased` +
		`) = (` +
		`EXCLUDED.username, EXCLUDED.id, EXCLUDED.score, EXCLUDED.dateandtime, EXCLUDED.erased` +
		`)`

	// run query
	XOLog(sqlstr, usm.Username, usm.ID, usm.Score, usm.Dateandtime, usm.Erased)
	_, err = db.Exec(sqlstr, usm.Username, usm.ID, usm.Score, usm.Dateandtime, usm.Erased)
	if err != nil {
		return err
	}

	// set existence
	usm._exists = true

	return nil
}

// Delete deletes the UserScoreMovie from the database.
func (usm *UserScoreMovie) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !usm._exists {
		return nil
	}

	// if deleted, bail
	if usm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.user_score_movie WHERE id = $1`

	// run query
	XOLog(sqlstr, usm.ID)
	_, err = db.Exec(sqlstr, usm.ID)
	if err != nil {
		return err
	}

	// set deleted
	usm._deleted = true

	return nil
}

// MovieMapping returns the MovieMapping associated with the UserScoreMovie's ID (id).
//
// Generated from foreign key 'movie_user_score_movie_fk'.
func (usm *UserScoreMovie) MovieMapping(db XODB) (*MovieMapping, error) {
	return MovieMappingByID(db, usm.ID)
}

// Useraccount returns the Useraccount associated with the UserScoreMovie's Username (username).
//
// Generated from foreign key 'useraccount_user_score_movie_fk'.
func (usm *UserScoreMovie) Useraccount(db XODB) (*Useraccount, error) {
	return UseraccountByUsername(db, usm.Username)
}

// UserScoreMovieByUsernameID retrieves a row from 'public.user_score_movie' as a UserScoreMovie.
//
// Generated from index 'pk_user_score_movie'.
func UserScoreMovieByUsernameID(db XODB, username string, id string) (*UserScoreMovie, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`username, id, score, dateandtime, erased ` +
		`FROM public.user_score_movie ` +
		`WHERE username = $1 AND id = $2`

	// run query
	XOLog(sqlstr, username, id)
	usm := UserScoreMovie{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, username, id).Scan(&usm.Username, &usm.ID, &usm.Score, &usm.Dateandtime, &usm.Erased)
	if err != nil {
		return nil, err
	}

	return &usm, nil
}
