// Package domain contains the types for schema 'public'.
package domain

// GENERATED BY XO. DO NOT EDIT.

import "errors"

// UserViewMovie represents a row from public.user_view_movie.
type UserViewMovie struct {
	Username    string // username
	ID          string // id
	Place       string // place
	Dateandtime int64  // dateandtime
	Erased      bool   // erased

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UserViewMovie exists in the database.
func (uvm *UserViewMovie) Exists() bool {
	return uvm._exists
}

// Deleted provides information if the UserViewMovie has been deleted from the database.
func (uvm *UserViewMovie) Deleted() bool {
	return uvm._deleted
}

// Insert inserts the UserViewMovie to the database.
func (uvm *UserViewMovie) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if uvm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_view_movie (` +
		`username, place, dateandtime, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) RETURNING id`

	// run query
	XOLog(sqlstr, uvm.Username, uvm.Place, uvm.Dateandtime, uvm.Erased)
	err = db.QueryRow(sqlstr, uvm.Username, uvm.Place, uvm.Dateandtime, uvm.Erased).Scan(&uvm.ID)
	if err != nil {
		return err
	}

	// set existence
	uvm._exists = true

	return nil
}

// Update updates the UserViewMovie in the database.
func (uvm *UserViewMovie) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !uvm._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if uvm._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.user_view_movie SET (` +
		`username, place, dateandtime, erased` +
		`) = ( ` +
		`$1, $2, $3, $4` +
		`) WHERE id = $5`

	// run query
	XOLog(sqlstr, uvm.Username, uvm.Place, uvm.Dateandtime, uvm.Erased, uvm.ID)
	_, err = db.Exec(sqlstr, uvm.Username, uvm.Place, uvm.Dateandtime, uvm.Erased, uvm.ID)
	return err
}

// Save saves the UserViewMovie to the database.
func (uvm *UserViewMovie) Save(db XODB) error {
	if uvm.Exists() {
		return uvm.Update(db)
	}

	return uvm.Insert(db)
}

// Upsert performs an upsert for UserViewMovie.
//
// NOTE: PostgreSQL 9.5+ only
func (uvm *UserViewMovie) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if uvm._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.user_view_movie (` +
		`username, id, place, dateandtime, erased` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`username, id, place, dateandtime, erased` +
		`) = (` +
		`EXCLUDED.username, EXCLUDED.id, EXCLUDED.place, EXCLUDED.dateandtime, EXCLUDED.erased` +
		`)`

	// run query
	XOLog(sqlstr, uvm.Username, uvm.ID, uvm.Place, uvm.Dateandtime, uvm.Erased)
	_, err = db.Exec(sqlstr, uvm.Username, uvm.ID, uvm.Place, uvm.Dateandtime, uvm.Erased)
	if err != nil {
		return err
	}

	// set existence
	uvm._exists = true

	return nil
}

// Delete deletes the UserViewMovie from the database.
func (uvm *UserViewMovie) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !uvm._exists {
		return nil
	}

	// if deleted, bail
	if uvm._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.user_view_movie WHERE id = $1`

	// run query
	XOLog(sqlstr, uvm.ID)
	_, err = db.Exec(sqlstr, uvm.ID)
	if err != nil {
		return err
	}

	// set deleted
	uvm._deleted = true

	return nil
}

// MovieMapping returns the MovieMapping associated with the UserViewMovie's ID (id).
//
// Generated from foreign key 'movie_user_view_movie_fk'.
func (uvm *UserViewMovie) MovieMapping(db XODB) (*MovieMapping, error) {
	return MovieMappingByID(db, uvm.ID)
}

// Useraccount returns the Useraccount associated with the UserViewMovie's Username (username).
//
// Generated from foreign key 'useraccount_user_view_movie_fk'.
func (uvm *UserViewMovie) Useraccount(db XODB) (*Useraccount, error) {
	return UseraccountByUsername(db, uvm.Username)
}

// UserViewMovieByUsernameID retrieves a row from 'public.user_view_movie' as a UserViewMovie.
//
// Generated from index 'pk_user_view_movie'.
func UserViewMovieByUsernameID(db XODB, username string, id string) (*UserViewMovie, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`username, id, place, dateandtime, erased ` +
		`FROM public.user_view_movie ` +
		`WHERE username = $1 AND id = $2`

	// run query
	XOLog(sqlstr, username, id)
	uvm := UserViewMovie{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, username, id).Scan(&uvm.Username, &uvm.ID, &uvm.Place, &uvm.Dateandtime, &uvm.Erased)
	if err != nil {
		return nil, err
	}

	return &uvm, nil
}
